FROM node:22-alpine

WORKDIR /app

# Install sharp dependencies
RUN apk add --no-cache \
    build-base \
    python3 \
    libc6-compat \
    vips-dev

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

EXPOSE 1337

CMD ["yarn", "develop"]
